version: '3.8'

services:
  market-sim:
    build: .
    container_name: market-sim-cli
    env_file:
      - .env      
    volumes:
      - ./:/app    
    command: ["--traders", "5", "--ticks", "50", "--init-price", "100.0"]
